import { useEffect, useState } from "react";
import { Plus, Search } from "lucide-react";
import Modal from "../components/Modal";
import { expenseAPI } from "../services/api";

export default function Expenses(){
 const [expenses,setExpenses]=useState([]),[show,setShow]=useState(false),[search,setSearch]=useState(""),[error,setError]=useState("");
 const [form,setForm]=useState({date:new Date().toISOString().slice(0,10),category:"",description:"",amount:"",payment:""});
 const load=async()=>{try{const {data}=await expenseAPI.getAll();setExpenses(data)}catch(e){setError(e.response?.data?.error||"Unable to load expenses.")}};
 useEffect(()=>{load()},[]);
 const add=async e=>{e.preventDefault();try{await expenseAPI.create({...form,amount:Number(form.amount)});setShow(false);setForm({date:new Date().toISOString().slice(0,10),category:"",description:"",amount:"",payment:""});load()}catch(e){setError(e.response?.data?.error||"Unable to save expense.")}};
 const filtered=expenses.filter(x=>(x.description||"").toLowerCase().includes(search.toLowerCase())||(x.category||"").toLowerCase().includes(search.toLowerCase()));
 return <div><div className="page-header"><div><h1>Expenses</h1><p>Track and manage business expenses</p></div><button className="primary-btn" onClick={()=>setShow(true)}><Plus size={16}/> Add Expense</button></div>{error&&<div className="error-message">{error}</div>}
 <div className="module-card"><div className="table-toolbar"><div className="table-search"><Search size={17}/><input placeholder="Search expenses..." value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="record-count">{filtered.length} Expenses</span></div><div className="table-wrapper"><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th>Payment</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.date}</td><td>{x.category}</td><td>{x.description}</td><td>₹{Number(x.amount).toLocaleString()}</td><td>{x.payment}</td></tr>)}</tbody></table></div></div>
 {show&&<Modal title="Add Expense" onClose={()=>setShow(false)}><form onSubmit={add}><div className="form-row"><div className="form-group"><label>Date</label><input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div><div className="form-group"><label>Category *</label><input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div></div><div className="form-group"><label>Description *</label><input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="form-row"><div className="form-group"><label>Amount *</label><input type="number" min="0" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div><div className="form-group"><label>Payment</label><select value={form.payment} onChange={e=>setForm({...form,payment:e.target.value})}><option value="">Select</option><option>Cash</option><option>Bank Transfer</option><option>UPI</option><option>Card</option></select></div></div><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setShow(false)}>Cancel</button><button className="primary-btn">Save Expense</button></div></form></Modal>}</div>;
}
