import { useEffect, useMemo, useState } from "react";
import { Plus, Trash2, ShoppingCart, Search } from "lucide-react";
import { customerAPI, productAPI, orderAPI } from "../services/api";

export default function Orders(){
 const [orders,setOrders]=useState([]),[customers,setCustomers]=useState([]),[products,setProducts]=useState([]),[show,setShow]=useState(false),[customerId,setCustomerId]=useState(""),[items,setItems]=useState([]),[selectedProduct,setSelectedProduct]=useState(""),[quantity,setQuantity]=useState(1),[search,setSearch]=useState(""),[error,setError]=useState("");
 const load=async()=>{try{const [o,c,p]=await Promise.all([orderAPI.getAll(),customerAPI.getAll(),productAPI.getAll()]);setOrders(o.data);setCustomers(c.data);setProducts(p.data)}catch(e){setError(e.response?.data?.error||"Unable to load orders.")}};
 useEffect(()=>{load()},[]);
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+i.price*i.quantity,0),[items]),tax=subtotal*.18,total=subtotal+tax;
 const addItem=()=>{const p=products.find(x=>x.id===Number(selectedProduct));if(!p||quantity<1)return;setItems([...items,{...p,quantity:Number(quantity)}]);setSelectedProduct("");setQuantity(1)};
 const create=async()=>{if(!customerId||!items.length)return setError("Select a customer and add products.");try{await orderAPI.create({customerId:Number(customerId),items:items.map(i=>({productId:i.id,quantity:i.quantity}))});setItems([]);setCustomerId("");setShow(false);load()}catch(e){setError(e.response?.data?.error||"Unable to create order.")}};
 const filtered=orders.filter(o=>(o.orderNumber||"").toLowerCase().includes(search.toLowerCase())||(o.customer?.name||"").toLowerCase().includes(search.toLowerCase()));
 return <div><div className="page-header"><div><h1>Orders</h1><p>Create and manage customer orders</p></div><button className="primary-btn" onClick={()=>setShow(true)}><Plus size={16}/> Create Order</button></div>{error&&<div className="error-message">{error}</div>}
 {!show?<div className="module-card"><div className="table-toolbar"><div className="table-search"><Search size={17}/><input placeholder="Search orders..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="table-wrapper"><table><thead><tr><th>Order ID</th><th>Customer</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id}><td><strong>{o.orderNumber}</strong></td><td>{o.customer?.name}</td><td>{o.orderDate?new Date(o.orderDate).toLocaleDateString():"—"}</td><td>₹{Number(o.total).toLocaleString()}</td><td><span className="status pending">{o.status}</span></td></tr>)}</tbody></table></div></div>:
 <div className="order-builder"><div className="builder-header"><div><h2>Create New Order</h2><p>Build the customer order and calculate billing automatically.</p></div><button className="secondary-btn" onClick={()=>setShow(false)}>Cancel</button></div>
 <div className="form-group"><label>Customer *</label><select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
 <div className="add-item-row"><div className="form-group"><label>Product</label><select value={selectedProduct} onChange={e=>setSelectedProduct(e.target.value)}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — ₹{p.price}</option>)}</select></div><div className="form-group quantity-input"><label>Quantity</label><input type="number" min="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></div><button className="add-item-btn" onClick={addItem}><Plus size={17}/> Add</button></div>
 <div className="order-items">{!items.length?<div className="empty-order"><ShoppingCart size={32}/><p>No products added to this order.</p></div>:<table><thead><tr><th>Product</th><th>Quantity</th><th>Unit Price</th><th>Total</th><th></th></tr></thead><tbody>{items.map((i,n)=><tr key={n}><td>{i.name}</td><td>{i.quantity}</td><td>₹{i.price}</td><td>₹{(i.price*i.quantity).toLocaleString()}</td><td><button className="delete-btn" onClick={()=>setItems(items.filter((_,x)=>x!==n))}><Trash2 size={16}/></button></td></tr>)}</tbody></table>}</div>
 <div className="bill-summary"><div><span>Subtotal</span><strong>₹{subtotal.toLocaleString()}</strong></div><div><span>Tax (18%)</span><strong>₹{tax.toLocaleString()}</strong></div><div className="bill-total"><span>Total</span><strong>₹{total.toLocaleString()}</strong></div></div><button className="primary-btn" onClick={create}>Create Order</button>
 </div>}</div>;
}
